;Language setup change to yours
lang = english
;Folder name for mass VPK mod fix (change it for whatever you want)
foldername = _VPKMODFIX
;Automation vaule: 1 = cache remover 2 = mod fix 0 = your choice(default one)
AutoVaule = 0